name: testarget
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^5.0.3
  dio: ^4.0.6
  equatable: ^2.0.3
  shared_preferences: ^2.0.15
  asuka: ^2.0.1+3
  flutter_screenutil: ^5.6.0
  dartz: ^0.10.1
  mobx: ^2.2.1
  flutter_mobx: ^2.2.0
  google_fonts: ^5.1.0
  url_launcher: ^6.1.10




  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png


